/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Asif
 */
public class userans extends javax.swing.JFrame {

    /**
     * Creates new form userans
     */
    public userans() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Question");

        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setText("jRadioButton2");

        jRadioButton3.setText("jRadioButton3");

        jRadioButton4.setText("jRadioButton4");

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton3)
                    .addComponent(jButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton4))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int temp=0,t1=0,t2=0,t3=0,t4=0,sum,t1p,t2p,t3p,t4p;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/survey", "root", "kaziatiq201");
            if (jRadioButton1.isSelected() == true) {
                PreparedStatement st = (PreparedStatement) con
                        .prepareStatement("Select option1 from ans where Q_ID=?");
                st.setInt(1, qid);
                ResultSet rs = st.executeQuery();
                if (rs.next())
                    temp = rs.getInt("option1");
                temp++;
                PreparedStatement pstmt = con.prepareStatement("update ans set option1=? where Q_ID=?");
                pstmt.setInt(1, temp);
                pstmt.setInt(2, qid);
                pstmt.executeUpdate();
            } else if (jRadioButton2.isSelected() == true) {
                PreparedStatement st = (PreparedStatement) con
                        .prepareStatement("Select option2 from ans where Q_ID=?");
                st.setInt(1, qid);
                ResultSet rs = st.executeQuery();
                if (rs.next())
                    temp = rs.getInt("option2");
                temp++;
                PreparedStatement pstmt = con.prepareStatement("update ans set option2=? where Q_ID=?");
                pstmt.setInt(1, temp);
                pstmt.setInt(2, qid);
                pstmt.executeUpdate();
            } else if (jRadioButton3.isSelected() == true) {
                PreparedStatement st = (PreparedStatement) con
                        .prepareStatement("Select option3 from ans where Q_ID=?");
                st.setInt(1, qid);

                ResultSet rs = st.executeQuery();
                if (rs.next())
                    temp = rs.getInt("option3");
                temp++;
                PreparedStatement pstmt = con.prepareStatement("update ans set option3=? where Q_ID=?");
                pstmt.setInt(1, temp);
                pstmt.setInt(2, qid);
                pstmt.executeUpdate();
            } else if (jRadioButton4.isSelected() == true) {
                PreparedStatement st = (PreparedStatement) con
                        .prepareStatement("Select option4 from ans where Q_ID=?");
                st.setInt(1, qid);
                ResultSet rs = st.executeQuery();
                if (rs.next())
                    temp = rs.getInt("option4");
                temp++;
                PreparedStatement pstmt = con.prepareStatement("update ans set option4=? where Q_ID=?");
                pstmt.setInt(1, temp);
                pstmt.setInt(2, qid);
                pstmt.executeUpdate();
            } else { }


            this.setVisible(false);
            results ob=new results();
            ob.result(qid);
            //new surveylist().setVisible(true);// TODO add your handling code here:
    }catch(Exception e){System.out.println(e);}}//GEN-LAST:event_jButton1ActionPerformed
    public void takedata(String ques,String q1,String q2,String q3,String q4,int q)
        {
            jLabel1.setText(ques);
            jRadioButton1.setText(q1);
            jRadioButton2.setText(q2);
            jRadioButton3.setText(q3);
            jRadioButton4.setText(q4);
            qid=q;
            return;
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userans().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    public int qid;
    // End of variables declaration//GEN-END:variables
}
